name: Deploy to Deta

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2
      
      - name: Log in to Deta and deploy the project
      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: ${{ secrets.DETA_NAME }}
          deta-project: ${{ secrets.DETA_PROJECT }}
          deta-project-dir: ${{ secrets.DETA_PROJECT_DIR }}
